{{- if and .Values.istio.enabled  .Values.monolith.enabled }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      {{- include "loki.matchLabels" . | nindent 6 }}
      release: {{ .Release.Name }}
{{- end }}
