{{- if and .Values.istio.enabled  (index .Values "loki-simple-scalable").enabled }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: loki-simple-scalable
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      {{- include "loki.matchLabels" . | nindent 6 }}
  portLevelMtls:
    # Monitoring exception
    {{- if and (eq .Values.istio.mtls.mode "STRICT") (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") (index .Values "loki-simple-scalable").serviceMonitor.enabled }}
    "3100":
      mode: PERMISSIVE
    {{- end }}
    # GRPC exception to support Loki internal communication
    "9095":
      mode: PERMISSIVE
{{- end }}
