{{- if and .Values.istio.enabled  (eq (include "loki.deployment.isSingleBinary" .) "true") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      {{- include "loki.selectorLabels" . | nindent 6 }}
{{- end }}
