{{- if and .Values.istio.enabled  (eq (include "loki.deployment.isSingleBinary" .) "false") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: loki-simple-scalable
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  portLevelMtls:
    # GRPC exception to support Loki internal communication
    "9095":
      mode: PERMISSIVE
{{- end }}
