{{- if and .Values.istio.enabled .Values.enterprise.enabled .Values.minio.enabled (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: loki-minio-endpoint-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: minio
      app.kubernetes.io/instance: {{ .Release.Name }}
  portLevelMtls:
    # Enterprise jobs exception
    "9000":
      mode: PERMISSIVE
{{- end }}
