{{- if and .Values.networkPolicies.enabled (not .Values.minio.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-external-services
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      {{- include "loki.matchLabels" . | nindent 4 }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
{{- end }}
