{{- if and .Values.networkPolicies.enabled .Values.minio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-minio-tenant-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: minio  
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
          {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
          # ONLY Block requests to cloud metadata IP
          except:
            - 169.254.169.254/32
          {{- end }}
{{- end }}
