{{- if and .Values.networkPolicies.enabled .Values.istio.enabled .Values.istio.loki.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-istio-ingressgateway-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: istio-controlplane
      podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicies.ingressLabels | nindent 10}}
    ports:
    - port: 3100
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
{{- end }}