{{- if and .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alloy-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{ include "loki.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: alloy
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: alloy
    ports:
      - port: 3100
        protocol: TCP
{{- end }}

