{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-grafana-gateway
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{ include "loki.gatewaySelectorLabels" . | nindent 6 }}
  ingress:
  - {}
  policyTypes:
  - Ingress
{{- end }}
