{{- if and (not (index .Values "read" "disabled")) (not (index .Values "write" "disabled")) }}
{{- if not .Values.loki.existingSecretForConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.name" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (mergeOverwrite (tpl .Values.loki.config . | fromYaml) .Values.loki.structuredConfig | toYaml) . | nindent 4 }}
{{- end -}}
{{- end -}}