{{- if .Values.global.createGlobalConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: loki-config
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki.yaml: {{ tpl .Values.global.config . | b64enc }}
{{- end }}
