---
loki:
  commonConfig:
    replication_factor: 1
  useTestSchema: true
  storage:
    bucketNames:
      chunks: loki
      ruler: loki
      admin: loki-admin
      deletion: loki-deletion
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1
