{{- if not .Values.global.existingSecretForConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  loki.yaml: |
    {{- tpl (toYaml .Values.loki.config) . | nindent 4 }}
{{- end -}}
