apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}-memberlist
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-memberlist
      port: 7946
      targetPort: tcp-memberlist
      protocol: TCP
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
