{{- if not .Values.experimentalMode.enabled }}
{{- if and (lt (int .Values.backend.replicas) 2) (ne .Values.deploymentMode "SingleBinary") }}
{{- fail "Loki backend.replicas must be set to 2 or greater." }}
{{- end }}

{{- if (lt (int .Values.backend.autoscaling.minReplicas) 2) }}
{{- fail "Loki backend.autoscaling.minReplicas must be set to 2 or greater." }}
{{- end }}
{{- end }}