{{- /* Render Istio Sidecar */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ .Release.Name }}-sidecar
  namespace: {{.Release.Namespace}}
  labels:
    {{ include "loki.labels" $ }}
spec:
  workloadSelector:
    labels:
      {{- include "loki.selectorLabels" $ | nindent 6 }}
  outboundTrafficPolicy:
    mode: {{ .Values.istio.hardened.outboundTrafficPolicyMode }}
{{- end }}
