{{- if and .Values.istio.enabled .Values.istio.loki.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "loki.name" . }}
    helm.sh/chart: {{ include "loki.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: loki
    app.kubernetes.io/component: networking
    {{- if .Values.istio.loki.labels }}
    {{ toYaml .Values.istio.loki.labels | indent 4 }}
    {{- end }}
  {{- if .Values.istio.loki.annotations }}
  annotations:
  {{- toYaml .Values.istio.loki.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.loki.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.loki.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
      {{- if or (eq .Values.deploymentMode "SimpleScalable") (eq .Values.deploymentMode "Distributed") }}
      - destination:
          port:
            number: {{ $.Values.gateway.service.port }}
          host: {{ include "loki.gatewayFullname" $ }}.{{ .Release.Namespace }}.svc.cluster.local
      {{- end }}
      {{- if eq .Values.deploymentMode "SingleBinary" }}
      - destination:
          port:
            number: {{ .Values.loki.server.http_listen_port }}
          host: {{ include "loki.singleBinaryFullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
      {{- end }}
{{- end }}
