{{- if .Values.gel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "enterprise-logs.gatewayFullname" . }}
  labels:
    {{- include "enterprise-logs.gatewayLabels" . | nindent 4 }}
    {{- with .Values.gel.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.gel.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.gel.gateway.replicas }}
  selector:
    matchLabels:
      {{- include "enterprise-logs.gatewaySelectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.gel.gateway.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "enterprise-logs.gatewaySelectorLabels" . | nindent 8 }}
        {{- with .Values.gel.gateway.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.gel.useExternalConfig }}
        checksum/config: {{ .Values.gel.externalConfigVersion }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- end}}
        {{- with .Values.gel.gateway.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "loki.serviceAccountName" . }}-gateway
      {{- if .Values.gel.gateway.priorityClassName }}
      priorityClassName: {{ .Values.gateway.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.gel.gateway.securityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.gel.gateway.initContainers | nindent 8 }}
      {{- if .Values.gel.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.gel.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}

      containers:
        - name: enterprise-logs
          image: "{{ template "enterprise-logs.image" . }}"
          imagePullPolicy: {{ .Values.gel.image.pullPolicy }}
          args:
            - -target=gateway
            - -config.file=/etc/loki/config/loki.yaml
            - -log.level=debug
            {{- if .Values.gel.gateway.useDefaultProxyURLs }}
            - -gateway.proxy.default.url=http://{{ template "loki.gatewayUrl" . }}.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.admin-api.url=http://{{ template "enterprise-logs.adminApiFullname" . }}.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.distributor.url=http://{{ template "loki.gatewayUrl" . }}.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.ingester.url=http://{{ template "loki.gatewayUrl" . }}.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.query-frontend.url=http://{{ template "loki.gatewayUrl" . }}.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.ruler.url=http://{{ template "loki.gatewayUrl" . }}.{{ .Release.Namespace }}.svc:3100
            {{- end }}
            {{- range $key, $value := .Values.gel.gateway.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: license
              mountPath: /etc/enterprise-logs/license
            - name: storage
              mountPath: /var
              subPath: {{ .Values.gel.gateway.persistence.subPath }}
            {{- if .Values.gel.gateway.extraVolumeMounts }}
            {{ toYaml .Values.gel.gateway.extraVolumeMounts | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.gel.gateway.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.gel.gateway.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.gel.gateway.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
            {{- if .Values.gel.gateway.env }}
            {{ toYaml .Values.gel.gateway.env | nindent 12 }}
            {{- end }}
        {{- with .Values.gel.gateway.extraContainers }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.gel.gateway.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.gel.gateway.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.gel.gateway.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.gel.gateway.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
          {{- if .Values.gel.useExternalConfig }}
            secretName: {{ .Values.gel.externalConfigName }}
          {{- else }}
            secretName: loki-config
          {{- end }}
        - name: license
          secret:
          {{- if .Values.gel.useExternalLicense }}
            secretName: {{ .Values.gel.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        - name: storage
          emptyDir: {}
        {{- if .Values.gel.gateway.extraVolumes }}
        {{ toYaml .Values.gel.gateway.extraVolumes | nindent 8 }}
        {{- end }}
{{- end}}