{{- $isSimpleScalable := eq (include "loki.deployment.isScalable" .) "true" -}}
{{- if $isSimpleScalable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.readFullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "loki.readLabels" . | nindent 4 }}
    {{- with .Values.loki.serviceLabels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.read.service.labels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  annotations:
    {{- with .Values.loki.serviceAnnotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.read.service.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3100
      targetPort: 3100
      protocol: TCP
    - name: grpclb
      port: 9095
      targetPort: 9095
      appProtocol: tcp
      protocol: TCP
  publishNotReadyAddresses: true
  selector:
    {{- include "loki.readSelectorLabels" . | nindent 4 }}
{{- end }}
