{{- if and .Values.gel.enabled (not .Values.gel.useExternalLicense) -}}
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-logs-license
  labels:
    {{- include "enterprise-logs.labels" . | nindent 4 }}
data:
  license.jwt: {{ .Values.gel.license.contents | b64enc }}
{{- end }}
