{{- if .Values.gel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "enterprise-logs.adminApiFullname" . }}
  labels:
    {{- include "enterprise-logs.adminApiLabels" . | nindent 4 }}
    {{- with .Values.gel.adminApi.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/part-of: memberlist
  annotations:
    {{- with .Values.gel.adminApi.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.gel.adminApi.replicas }}
  selector:
    matchLabels:
      {{- include "enterprise-logs.adminApiSelectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.gel.adminApi.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "enterprise-logs.adminApiSelectorLabels" . | nindent 8 }}
        {{- with .Values.gel.adminApi.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/part-of: memberlist
      annotations:
        {{- if .Values.gel.useExternalConfig }}
        checksum/config: {{ .Values.gel.externalConfigVersion }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- end}}
        {{- with .Values.gel.adminApi.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "loki.serviceAccountName" . }}
      {{- if .Values.gel.adminApi.priorityClassName }}
      priorityClassName: {{ .Values.gel.adminApi.priorityClassName }}
      {{- end }}
      {{- if .Values.gel.adminApi.securityContext.runAsGroup }}
      securityContext:
        fsGroup: {{ .Values.gel.adminApi.securityContext.runAsGroup | int }}
      {{- end}}
      {{- if .Values.gel.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.gel.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: enterprise-logs
          image: "{{ template "enterprise-logs.image" . }}"
          imagePullPolicy: {{ .Values.gel.image.pullPolicy }}
          args:
            - -target=admin-api
            - -config.file=/etc/loki/config/loki.yaml
            {{- range $key, $value := .Values.gel.adminApi.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: license
              mountPath: /etc/enterprise-logs/license
            - name: storage
              mountPath: /var
              subPath: {{ .Values.gel.adminApi.persistence.subPath }}
            {{- if .Values.gel.adminApi.extraVolumeMounts }}
            {{ toYaml .Values.gel.adminApi.extraVolumeMounts | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: tcp-memberlist
              containerPort: 7946
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.gel.adminApi.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.gel.adminApi.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.gel.adminApi.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            {{- toYaml .Values.gel.adminApi.securityContext | nindent 12 }}
          env:
            {{- if .Values.gel.adminApi.env }}
            {{ toYaml .Values.gel.adminApi.env | nindent 12 }}
            {{- end }}
        {{- with .Values.gel.adminApi.extraContainers }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.gel.adminApi.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.gel.adminApi.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.gel.adminApi.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.gel.adminApi.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
          {{- if .Values.gel.useExternalConfig }}
            secretName: {{ .Values.gel.externalConfigName }}
          {{- else }}
            secretName: loki-config
          {{- end }}
        - name: license
          secret:
          {{- if .Values.gel.useExternalLicense }}
            secretName: {{ .Values.gel.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        - name: storage
          emptyDir: {}
        {{- if .Values.gel.adminApi.extraVolumes }}
        {{ toYaml .Values.gel.adminApi.extraVolumes | nindent 8 }}
        {{- end }}
{{- end}}