{{- if .Values.gel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise-logs.adminApiFullname" . }}
  labels:
    {{- include "enterprise-logs.adminApiLabels" . | nindent 4 }}
    {{- with .Values.gel.adminApi.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.gel.adminApi.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: {{ .Values.gel.adminApi.service.port }}
      protocol: TCP
      targetPort: {{ .Values.gel.adminApi.service.targetPort }}
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: grpc
  selector:
    {{- include "enterprise-logs.adminApiSelectorLabels" . | nindent 4 }}
{{- end}}